name: Cypress Pipeline (parallel execution)

on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # ✅ Correct placement

jobs:
  cypress-run:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: [chrome]
        spec:
          - login2.feature
          - newtours.feature
          - amazon.feature

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: |
          npx cypress run \
          --spec="cypress/e2e/${{ matrix.spec }}"
         # --browser ${{ matrix.browser }} \
          

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline
          allure generate allure-results --clean -o allure-report

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report